/* prettier-ignore-start */

/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router
import { createFileRoute } from "@tanstack/react-router";

// Import Routes
import { Route as rootRoute } from "./routes/__root";
import { Route as ContestsContestSlugImport } from "./routes/contests.$contestSlug";
import { Route as ReportReportIdImport } from "./routes/report.$reportId";

// Create Virtual Routes

const IndexLazyImport = createFileRoute("/")();

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
    path: "/",
    getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

const ReportReportIdRoute = ReportReportIdImport.update({
    path: "/report/$reportId",
    getParentRoute: () => rootRoute,
} as any);

const ContestsContestSlugRoute = ContestsContestSlugImport.update({
    path: "/contests/$contestSlug",
    getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/": {
            id: "/";
            path: "/";
            fullPath: "/";
            preLoaderRoute: typeof IndexLazyImport;
            parentRoute: typeof rootRoute;
        };
        "/contests/$contestSlug": {
            id: "/contests/$contestSlug";
            path: "/contests/$contestSlug";
            fullPath: "/contests/$contestSlug";
            preLoaderRoute: typeof ContestsContestSlugImport;
            parentRoute: typeof rootRoute;
        };
        "/report/$reportId": {
            id: "/report/$reportId";
            path: "/report/$reportId";
            fullPath: "/report/$reportId";
            preLoaderRoute: typeof ReportReportIdImport;
            parentRoute: typeof rootRoute;
        };
    }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
    IndexLazyRoute,
    ContestsContestSlugRoute,
    ReportReportIdRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contests/$contestSlug",
        "/report/$reportId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/contests/$contestSlug": {
      "filePath": "contests.$contestSlug.tsx"
    },
    "/report/$reportId": {
      "filePath": "report.$reportId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
